name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: pynnie/sh-webdesign-toolkit/.github/workflows/ci-next.yml@v1
    with:
      run_smoke_tests: true
    secrets: inherit
